### ISSUE TITLE
d3-color vulnerable to ReDoS

### ISSUE THREAD

**Issue by LilithElina** [d3/d3-interpolate#106]
Is there any chance of an update to a less vulnerable version of d3-color? See the [vulnerability report here](https://github.com/advisories/GHSA-36jr-mh4h-2g58).

**Comment by darcyparker** [comment]
The `package.json` looks fine. But the [yarn.lock](https://github.com/d3/d3-interpolate/blob/main/yarn.lock#L272) is pointing to 3.0.1.  It needs to be 3.1.0.

**Comment by Waylon-Firework** [comment]
why closed
