### ISSUE TITLE
d3-color version issue

### ISSUE THREAD

**Issue by paladin0** [d3/d3-interpolate#108]
[d3-color](https://www.npmjs.com/package/d3-color)

hey guys i just ran npm audit and there is a dep issue on d3-color and it is high

any chance someone can confirm if they are getting the same issue?

**Comment by juztinlazaro** [comment]
any news? or specific version fixed version?

**Comment by curran** [comment]
I believe this may be related to

https://github.com/d3/d3-color/issues/97

which was fixed in

https://github.com/d3/d3-color/pull/100
