### ISSUE TITLE
Meteor app crashes

### ISSUE THREAD

**Issue by sbilgil** [d3/d3-interpolate#116]
In one of the project nivo is used. In one component nivo pie component used. And nivo-pie.es.js use components from @nivo/core and in nivo-core.es.js there is a code like : 
`var useAnimatedPath = function useAnimatedPath(path) {
  var _useMotionConfig = useMotionConfig(),
      animate = _useMotionConfig.animate,
      springConfig = _useMotionConfig.config;
  var previousPath = usePrevious(path);
  var interpolator = useMemo(function () {
    return interpolateString(previousPath, path);
  }, [previousPath, path]);
  var _useSpring = useSpring({
    from: {
      value: 0
    },
    to: {
      value: 1
    },
    reset: true,
    config: springConfig,
    immediate: !animate
  }),
      value = _useSpring.value;
  return to(value, interpolator);
};`
where d3-interpolate's part of interpolateString is used. And our app(written in meteor which dynamically create components i guess) is dockerized and used. But if it is used in linux chrome or windows edge it is ok. but when used in other browsers it fails with below error : 
`TypeError: ((c && c.eval) || eval)(...).apply is not a function
t http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1975
    g http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    q http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    resolve http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    o http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:9
    module /node_modules/d3-interpolate/src/value.js:1
    t http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1975
    g http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    n http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    o http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:9
    module /node_modules/d3-interpolate/src/index.js:1
    t http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1975
    g http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    n http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    o http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:9
    module /node_modules/@nivo/core/dist/nivo-core.es.js:1
    t http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1975
    g http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    n http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    o http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:9
    module /node_modules/@nivo/pie/dist/nivo-pie.es.js:1
    t http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1975
    g http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    n http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    o http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:9
    module /imports/ui/components/charts/PieChart.jsx:1
    t http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1975
    g http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    n http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    o http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:9
    module /imports/ui/components/analytics/AnalyticsCard.jsx:1
    t http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1975
    g http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    n http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    o http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:9
    module /imports/ui/components/analytics/AnalyticsDashboard.jsx:1
    t http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1975
    g http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    n http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:7
    o http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:9
    h http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1975
    t http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1975
    bindEnvironment http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1
    promise callback*n/t.makeCompatible/n.prototype.then http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1971
    dynamicImport http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1975
    D http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:2093
    Mi http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:69
    Qo http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:69
    fs http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:69
    ds http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:69
    Zs http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:69
    Ys http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:69
    Vs http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:69
    ys http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:69
    _o http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:69
    bindEnvironment http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1
    promise callback*n/t.makeCompatible/n.prototype.then http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:1971
    onNewData http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    next http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    M http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    A http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    e http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    K http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    K http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    next http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    i http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    ie http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    broadcastQueries http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    broadcastQueries http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    broadcastQueries http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    m http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    next http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    M http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    A http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    e http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    next http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    next http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    M http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    A http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    e http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    next http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165
    M http://178.242.135.26:20004/88290784a54f278964783d4f4f504506f3255c34.js?meteor_js_resource=true:165`

**Comment by Fil** [comment]
closing as not actionnable; this might be a question for nivo or meteor; or, see how to [get support](https://d3js.org/community#getting-help) with D3.
