### ISSUE TITLE
Gamma correct RGB interpolation

### ISSUE THREAD

**Issue by vorg** [d3/d3-interpolate#14]
Are you considering adding it in the future?

Interpolating RGB values without gamma correct produces darker "dirtier" colors than they should be.

<img width="325" alt="screen shot 2016-01-07 at 11 14 52" src="https://cloud.githubusercontent.com/assets/171001/12169407/22725e5e-b530-11e5-8978-583460f068d8.png">

The solution would be to move values to linear space, interpolate and bring it back to gamma space. 

```javascript
//pseudocode for R channel
var color_hex = '#FF0000';
var color = hex2bytes(color_hex);
var byte_r = color[0];
var float_r = byte_r/255;
var linear_r = Math.pow(float_r, 2.2);
var inter_r = interpolate(linear_r, linear_r_2, t);
var gamma_r = Math.pow(inter_r, 1/2.2);
var out_r = Math.floor(gamma_r * 255);
```

**Comment by mbostock** [comment]
This would be lovely. I’d recommend adopting an optional gamma parameter for interpolateRgbGamma, similar to what is done for Cubehelix interpolation.

**Comment by mbostock** [comment]
Your test case, above; my implement, below:

![screen shot 2016-02-02 at 12 51 04 pm](https://cloud.githubusercontent.com/assets/230541/12763869/aabee4fa-c9ab-11e5-9297-48d971776bd3.png)

**Comment by vorg** [comment]
Nice one. Thanks

**Comment by mbostock** [comment]
Thanks for the suggestion. :)
