### ISSUE TITLE
Add each interpolate as their own file in build

### ISSUE THREAD

**Issue by Calvein** [d3/d3-interpolate#2]
I think it would be great to not have to get all the interpolation methods when we just want one (it's linked to https://github.com/d3/d3-color/issues/15)
Lodash does it very well:
```js
// load the modern build
var _ = require('lodash');
// or a method category
var array = require('lodash/array');
// or a method (great for smaller builds with browserify/webpack)
var chunk = require('lodash/array/chunk');
```

So it would mean that instead of:
```js
var interpolateRound = require('d3-interpolate').interpolateRound
```

We could do:

```js
var interpolateRound = require('d3-interpolate/interpolateRound')
```

Which, in this case, is 630 less loc to add to the final build.
I think it might be a problem with all the new d3 repos, I'm happy to add PRs this week if you're keen with the change.

**Comment by mbostock** [comment]
Please do this by creating your own index.js file (or editing the existing one) and running [d3-bundler](https://github.com/d3/d3-bundler) (which is just a thin wrapper on [Rollup](https://github.com/rollup/rollup)). I have no plans to supports finer-grained modules using anything other than ES6 modules.
