### ISSUE TITLE
Update readme for interpolateTransformSvg

### ISSUE THREAD

**Issue by meeple142** [d3/d3-interpolate#21]
In d3 version 3.5.17 there is no interpolateTransformSvg but there is interpolateTransform. The readme for this repository has it as interpolateTransformSvg. It might be the up and coming api, so it might not really be an issue, but thought that I would let you know anyway. 

Thank you for such an awesome library!

**Comment by mbostock** [comment]
If you want the D3 3.x API, see the [D3 3.x API Reference](https://github.com/d3/d3/wiki/API-Reference) and specifically [d3.interpolateTransform](https://github.com/d3/d3/wiki/Transitions#d3_interpolateTransform).

If you want the D3 4.0 API, see the [D3 4.0 API Reference](https://github.com/d3/d3/blob/master/README.md#api-reference) and specifically [d3-interpolate](https://github.com/d3/d3-interpolate/blob/master/README.md), [d3.interpolateTransformSvg](https://github.com/d3/d3-interpolate/blob/master/README.md#interpolateTransformSvg) and [d3.interpolateTransformCss](https://github.com/d3/d3-interpolate/blob/master/README.md#interpolateTransformCss).

Release notes that describe the changes between D3 3.x and 4.0 will be made available when D3 4.0 is officially released. At the same time, a notice will be added to D3 3.x wiki pointing to the new D3 4.0 API references.

**Comment by meeple142** [comment]
Great! Thank you for the quick response and the clarification!
