### ISSUE TITLE
Interpolation questions

### ISSUE THREAD

**Issue by codepunkt** [d3/d3-interpolate#33]
Are all the interpolations linear?
Is it possible to do easing or even physics-based (e.g. spring based using stiffness and damping)?

**Comment by mbostock** [comment]
Most of the interpolators are linear, but not all (such as interpolateZoom and interpolateRgbBasis). See [d3-ease](https://github.com/d3/d3-ease) for easing.

If you have a question about D3’s behavior and want to discuss it with other users, consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by codepunkt** [comment]
Thanks @mbostock. Will do! :)
