### ISSUE TITLE
support for Vec3

### ISSUE THREAD

**Issue by morandd** [d3/d3-interpolate#38]
THREE.js and AFrame interchange between strings and Vec3 objects e.g
  `3 3 3` and {x:3, y:3, z:3}

I've been handling this using my own home-rolled interpolator functions with attrTween, but this seems like a straighforward feature to consider adding to stock d3.

**Comment by mbostock** [comment]
Not sure I understand this request; you’ll need to provide a more specific example of the functionality you want. This library isn’t intended to support parsing or interchange between formats, though you can interpolate strings with embedded numbers (d3.interpolateString) and arrays (d3.interpolateArray) or objects (d3.interpolateObject).

That said, perhaps you are asking for interpolation of typed arrays? I’ve opened #39 to track that.
