### ISSUE TITLE
Interpolate typed arrays?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-interpolate#39]
It’d be nice if there were an interpolator for typed arrays, like Float32Array. The existing d3.interpolateArray is *almost* what we want—the only change you’d need to make is to say `c = new b.constructor(nb)` rather than `c = new Array(nb)`.

However, there are two considerations with this approach:

- [ ] Should d3.interpolate delegate to d3.interpolateArray if *b* is a typed array? If so, we will need to use a different test than Array.isArray that also returns true for typed arrays.

- [ ] How should d3.interpolateArray behave if *b* is not an array and not a typed array? The current implementation is guaranteed to return an Array even if *b* is not an array (but may be an array-like). If *c* is constructed using *b*.constructor, the change to d3.interpolateArray might be considered backwards-incompatible.

It might make more sense to introduce a new d3.interpolateTypedArray, and keep the current behavior of d3.interpolateArray. And we could optionally extend d3.interpolate to delegate to d3.interpolateTypedArray for typed array input. Seems like the following test would work:

```js
function isTypedArray(x) {
  return ArrayBuffer.isView(x) && !(x instanceof DataView);
}
```

**Comment by chadbr** [comment]
Hey @mbostock  -- any thoughts on typed array support? We have a lot of "bulk" data we'd like to be about to pass directly to D3...

**Comment by Fil** [comment]
interpolateArray would not handle typed arrays with 10 or 100 millions of rows. Indeed above 1e6 values it starts to crumble.

An implementation with typed arrays:
https://observablehq.com/d/4a42579f12a84f89

**Comment by Fil** [comment]
@chadbr please see the pull-request #65 and test at https://observablehq.com/d/d966cf85471db4f7

**Comment by chadbr** [comment]
@Fil awesome :)

**Comment by mbostock** [comment]
Added interpolateNumberArray and typed array detection in #77.
