### ISSUE TITLE
Images in readme not loading?

### ISSUE THREAD

**Issue by tjrileywisc** [d3/d3-interpolate#47]
Might be a temporary github issue, but I'm not seeing any of the images here. Dev console shows something like this over and over:

`Refused to load the image 'https://raw.githubusercontent.com/d3/d3-interpolate/master/img/hsl.png' because it violates the following Content Security Policy directive: "img-src 'self' data: assets-cdn.github.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com collector.githubapp.com avatars0.githubusercontent.com avatars1.githubusercontent.com avatars2.githubusercontent.com avatars3.githubusercontent.com github-cloud.s3.amazonaws.com".`

**Comment by mbostock** [comment]
GitHub changed their Content-Security-Policy header and broke the images in all the D3 readmes. I’ve sent a request to support to see how they recommend fixing it.

**Comment by mbostock** [comment]
GitHub has put *.githubusercontent.com back in their Content Security Policy for img-src and all is now well in the world.
