### ISSUE TITLE
interpolateTransform* can't interpolate rotation from 0 to 360 deg

### ISSUE THREAD

**Issue by iseeyou911** [d3/d3-interpolate#48]
Hello
interpolateTransform*  interpolate rotation with shortest path. So, looks like it's imposible to make interpolation from 0 to 360 deg. I think this is an issue.

https://github.com/d3/d3-interpolate/blob/255231b98906040648eab089f4f1cdce3f489b9b/src/transform/index.js#L21

**Comment by danburzo** [comment]
@iseeyou911 this behavior matches [the CSS spec](https://drafts.csswg.org/css-transforms/#interpolation-of-decomposed-2d-matrix-values)

**Comment by mbostock** [comment]
Duplicate of #44.
