### ISSUE TITLE
The ending value may not be exact due to floating point arithmetic.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-interpolate#73]
In many cases in this library we use the interpolated value

```
a + (b - a) * t
```

This can return a value not equal to *b* when *t* = 1. If we want to guarantee that the exact value *b* is returned for *t* = 1, we should instead use the formula

```
a * (1 - t) + b * t
```

**Comment by mbostock** [comment]
@fil Should we take a crack at this?

**Comment by Fil** [comment]
I was under the impression that this was a kind of optimisation (doing substractions once—probably ultra negligible). Also, the substraction was a nuisance when working with Uint32 numbers…

In any case, I think having exact ends is desirable.
