### ISSUE TITLE
interpolateNumberArrayRound ?

### ISSUE THREAD

**Issue by Fil** [d3/d3-interpolate#78]
I just realized that in #77, for integer arrays, the implicit rounding is `floor` when we would want `round`, for symmetry.
I'm not sure where to put that change: in array type detection, and/or in an explicit interpolateNumberArrayRound function.

(Sorry for [l'esprit d'escalier](https://www.urbandictionary.com/define.php?term=Spirit%20of%20the%20Staircase))

**Comment by mbostock** [comment]
Feels too niche to me.

**Comment by Fil** [comment]
I would have liked the symmetry, but it's not that easy to code.
