### ISSUE TITLE
interpolateBalanced?

### ISSUE THREAD

**Issue by Fil** [d3/d3-interpolate#79]
interpolateRound(0,2) gives more space to intermediate values (1) than to the ends (0 and 2). interpolateBalanced would give them equal space.

<img width="447" alt="Capture d’écran 2019-11-21 à 07 10 30" src="https://user-images.githubusercontent.com/7001/69311990-0cbd8f80-0c2e-11ea-9ea2-81d0b8b5b935.png">

See https://observablehq.com/@fil/interpolatebalanced

**Comment by mbostock** [comment]
Feels too niche to me.

**Comment by jrus** [comment]
Can’t you just..

    draw(interpolateRound(-0.5, 2.5))

**Comment by Fil** [comment]
No, there are tiny bugs with that formula (at the ends, in your case -0 (sort-of okay) and 3 ❌).

but we can adapt it a bit:
```
interpolateBalanced = (a, b) => {
  // epsilon is needed to have an exact value for t=1
  var sign = Math.sign(b - a);
  return interpolateRound(
    a - sign * (0.5 - epsilon),
    b + sign * (0.5 - epsilon)
  );
}
```
